// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejmbwemerkdmqyrspijz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbWJ3ZW1lcmtkbXF5cnNwaWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNDg1NTAsImV4cCI6MjA3NjgyNDU1MH0.LqaUvRquILI-T5hGtyNf2ZsRyeyjA2qaBb1BQqGsykY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});